```{r setup, include=FALSE}
library(here)
library(scales)
library(tidyverse)

theme_set(theme_bw())

knitr::opts_chunk$set(echo = TRUE)
```

```{r load-counts}
install.packages("here")
library(here)
library(readr)
notes <-read_tsv("C:/Users/ds3/Downloads/community-notes-2025-group-4/data/notes.tsv")
ratings <- read_tsv("C:/Users/ds3/Downloads/community-notes-2025-group-4/data/ratings.tsv")
#9360 notes which is not 11000 so... a little less than
nrow(notes)
```

```{r-data-cleaning}
notes <- notes |> mutate(datetime = as.POSIXct(createdAtMillis / 1000, origin = "1970-01-01", tz = "UTC")) #convert to a datetime format from milliseconds
notes <- notes |> mutate(is_misleading = (misleadingOther == 1 | misleadingFactualError == 1 | misleadingManipulatedMedia ==1 | misleadingOutdatedInformation ==1 | misleadingMissingImportantContext == 1 | misleadingUnverifiedClaimAsFact == 1 | misleadingSatire == 1 ) )
notes <- notes |> mutate(is_notmisleading = (notMisleadingOther ==1 | notMisleadingFactuallyCorrect==1 | notMisleadingOutdatedButNotWhenWritten == 1 | notMisleadingClearlySatire==1 | notMisleadingPersonalOpinion ==1))
```
plot figure 2 misleading vs not misleading notes then by trustworthy and not trustworthy sources
```{r-plot-figure2}
notes$trustworthySources <- as.factor(notes$trustworthySources)
labels <- c("Misleading", "Not Misleading")
ggplot(notes, aes(x = is_misleading, fill = trustworthySources)) +
  geom_bar(stat = "count", position = "stack") +
  coord_flip() +
  theme(legend.title = element_blank()) +
  theme(axis.title = element_blank()) +
  scale_x_discrete(label = labels) +
  scale_fill_manual(labels=c("No trustworthy sources", "trustworthy sources"), values = c("yellow", "blue"))

```

figure 7 a 
```{r-fig7a}
#ccdf
colnames(notes)
colnames(ratings)
 
ratings_with_votes_per_note <- ratings |>
  select(noteId) |>
  group_by(noteId) |>
  summarize(votes_per_note = n())

joined_raings_notes <- inner_join(notes, ratings_with_votes_per_note, by = "noteId")
 
joined_raings_notes |>
  select(classification, votes_per_note) |>
  arrange(votes_per_note) |>
  group_by(classification) |>
  mutate(total_votes_each_category = sum(votes_per_note)) |>
  mutate(fraction_votes = votes_per_note/total_votes_each_category) |>
  mutate(cdf_fraction = cumsum(fraction_votes)) |>
  mutate(ccdf_percent = (1 - cdf_fraction) * 100)|>
  filter(ccdf_percent > 0) |>
  ggplot(aes(x = votes_per_note, y = ccdf_percent, color = classification)) +
  geom_line() +
  scale_y_log10(limits = c(0.01, 100), label=comma) 

```
```{r-fig7a}
ratings_2 <- ratings |> group_by(noteId) |> summarize(total_helpful = sum(helpful), total_unhelpful = sum(notHelpful)) |> mutate(total=total_helpful + total_unhelpful, ratio_helpful = total_helpful/total)
ccdf_ratio <- inner_join(notes, ratings_2) |> group_by(classification) |> arrange(ratio_helpful) |> mutate(rank=min_rank(ratio_helpful), n=n() ccdf=(1-((rank-1)/n)) *100) |> filter(ccdf != "Invalid Number")

ggplot(ccdf_ratio, aes(x=ratio_helpful, y=ccdf, color=classification)) + geom_line()
```





```{r-fig7a-badway}
joined_ratings_notes <- merge(notes, ratings, by = "noteId")
ratio <- joined_ratings_notes |> group_by(noteId, is_misleading) |> summarize(helpful_count = sum(helpful),total_votes = n()) |> select(noteId, is_misleading, helpful_count, total_votes)
ratio <- ratio |> mutate(ratio_helpful = helpful_count/total_votes) |> arrange(ratio_helpful)
ratio_ccdf <- ratio |> group_by(is_misleading) |> mutate(cdf_fraction = cumsum(ratio_helpful)/sum(ratio_helpful)) |> mutate(ccdf_fraction = (1- cdf_fraction) * 100) 
 #|> filter(ccdf_fraction > 0)


ggplot(ratio_ccdf, aes(x=ratio_helpful, y=ccdf_fraction, color=is_misleading)) +
geom_line() +
scale_y_log10(limits = c(0.01, 100), label=comma)
```
