
## Setting up the environment
```{r setup, include=FALSE}

library(here)
library(readr)
library(scales)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(broom)


theme_set(theme_bw())

knitr::opts_chunk$set(echo = TRUE)
```

## Loading notes and ratings
```{r load-counts}

notes <- read_tsv("./data/notes.tsv")
head(notes)
nrow(notes)
colnames(notes)

ratings <- read_tsv("./data/ratings.tsv")
nrow(ratings)
head(ratings)

```


## joining the notes and ratings

```{r join-notes-ratings}
notes_ratings <- left_join(notes, ratings, by="noteId")
notes_ratings

```


## Figure 2 Plot
```{r figure-2}

```


## Figure 3 Plot
```{r figure-3}

notes |>
    select("misleadingOther", "misleadingFactualError", "misleadingManipulatedMedia", "misleadingOutdatedInformation","misleadingMissingImportantContext", "misleadingUnverifiedClaimAsFact", "misleadingSatire")  |>
    rename("Other" = "misleadingOther", "Factual error" = "misleadingFactualError", "Manipulated media" = "misleadingManipulatedMedia", "Outdated information" = "misleadingOutdatedInformation", "Missing important contex" = "misleadingMissingImportantContext", "Unverified claim as fact" = "misleadingUnverifiedClaimAsFact", "Satire" = "misleadingSatire")|>
    colSums() |>
    tibble::enframe(name = "category", value = "total_count") |>
    ggplot(aes(y =reorder(category, total_count, FUN = sum, decreasing = FALSE), x = total_count)) +
    geom_bar(stat = "identity", fill="darkred") +
    xlab("Number of Birdwatch Notes") +
    ylab("") +
    scale_x_continuous(breaks = seq(0, 5500, by = 2000))
```



## Figure 4 Plot
```{r figure-4}
colnames(notes)

notes |>
  select("notMisleadingOther", "notMisleadingFactuallyCorrect", "notMisleadingOutdatedButNotWhenWritten","notMisleadingClearlySatire", "notMisleadingPersonalOpinion") |>
  rename("Other" = "notMisleadingOther", "Factually correct" = "notMisleadingFactuallyCorrect", "Outdated but not when written" = "notMisleadingOutdatedButNotWhenWritten", "Clearly satire" = "notMisleadingClearlySatire", "Personal opinion" = "notMisleadingPersonalOpinion") |>
  colSums() |>
  tibble::enframe(name = "category", value = "total_count") |>
  ggplot(aes(y =reorder(category, total_count, FUN = sum, decreasing = FALSE), x = total_count)) +
  geom_bar(stat = "identity", fill="blue") +
  xlab("Number of Birdwatch Notes") +
  ylab("") +
  scale_x_continuous(breaks = seq(0, 1000, by = 200))


```




## Figure 5c Plot
```{r figure-5c-incorrect}


# generating word count from summary
# notes_classification_word_count <- notes |>
#   mutate(word_count = str_count(notes$summary, '\\w+')) |>
#   select(classification, word_count) |> mutate(classification = case_when(
#     classification == "MISINFORMED_OR_POTENTIALLY_MISLEADING" ~ "Misleading",
#     classification == "NOT_MISLEADING" ~ "Not Misleading"
#   ))

# notes_classification_word_count  |>
#   drop_na() |>
#   arrange(word_count) |>
#   group_by(classification) |>
#   mutate(total_each_category = sum(word_count)) |>
#   mutate(fraction_word_count = word_count/total_each_category) |>
#   mutate(cdf_fraction = cumsum(fraction_word_count)) |>
#   mutate(ccdf_percent = (1 - cdf_fraction) * 100)|>
#   filter(ccdf_percent > 0) |>
#   ggplot(aes(x = word_count, y = ccdf_percent, color = classification)) +
#   geom_line() +
#   scale_y_log10(limits = c(0.01, 100), label=comma) 



  

```

```{r figure-5c-correct}
# generating word count from summary
notes_classification_word_count <- notes |>
  mutate(word_count = str_count(summary, '\\w+')) |>
  select(noteId, classification, word_count, trustworthySources) |>
  mutate(classification = case_when(
    classification == "MISINFORMED_OR_POTENTIALLY_MISLEADING" ~ "Misleading",
    classification == "NOT_MISLEADING" ~ "Not Misleading"
  ))

notes_classification_word_count |>
  drop_na(word_count) |>
  group_by(classification) |>
  arrange(word_count) |>
  # Calculate CCDF using the rank of each note
  mutate(n = n(),
         rank = row_number(),
         ccdf_percent = (1 - (rank - 1) / n) * 100) |>
  filter(ccdf_percent > 0) |>
  ggplot(aes(x = word_count, y = ccdf_percent, color = classification)) +
  geom_line() +
  scale_y_log10(limits = c(0.01, 100), label=scales::comma) +
  labs(
    x = "Word Count",
    y = "CCDF (%)"
  )

```




## Figure 7 Plots

```{r figure-7a}

```



 

```{r figure-7b}

colnames(notes)
colnames(ratings)

ratings_with_votes_per_note <- ratings |>
  select(noteId) |>
  group_by(noteId) |>
  summarize(votes_per_note = n())

max(ratings_with_votes_per_note$votes_per_note)

joined_raings_notes <- inner_join(notes, ratings_with_votes_per_note, by = "noteId")

joined_raings_notes |>
  select(classification, votes_per_note) |>
  mutate(classification = case_when(
    classification == "MISINFORMED_OR_POTENTIALLY_MISLEADING" ~ "Misleading",
    classification == "NOT_MISLEADING" ~ "Not Misleading"
  )) |>
  group_by(classification) |>
  arrange(votes_per_note) |>
  mutate(n = n(),
         rank = row_number(),
         ccdf_percent = (1 - (rank - 1) / n) * 100) |>
  filter(ccdf_percent > 0) |>
  ggplot(aes(x = votes_per_note, y = ccdf_percent, color = classification)) +
  geom_line() +
  scale_y_log10(limits = c(0.01, 100), label=scales::comma)



# joined_raings_notes |>
#   select(classification, votes_per_note) |>
#   mutate(classification = case_when(
#     classification == "MISINFORMED_OR_POTENTIALLY_MISLEADING" ~ "Misleading",
#     classification == "NOT_MISLEADING" ~ "Not Misleading"
#   )) |>
#   arrange(votes_per_note) |>
#   group_by(classification) |>
#   mutate(total_votes_each_category = sum(votes_per_note)) |>
#   mutate(fraction_votes = votes_per_note/total_votes_each_category) |>
#   mutate(cdf_fraction = cumsum(fraction_votes)) |>
#   mutate(ccdf_percent = (1 - cdf_fraction) * 100)|>
#   filter(ccdf_percent > 0) |>
#   ggplot(aes(x = votes_per_note, y = ccdf_percent, color = classification)) +
#   geom_line() +
#   scale_y_log10(limits = c(0.01, 100), label=comma) 
  
  

```

```{r }



```





## Figure 8 Plot
```{r figure-8}
colnames(ratings)


# doesn't include Unbiased language as no one chooses this opiton
ratings |>
    select("helpfulOther", "helpfulInformative", "helpfulClear", "helpfulEmpathetic", "helpfulGoodSources", "helpfulUniqueContext", "helpfulAddressesClaim", "helpfulImportantContext")  |>
    rename("Other" = "helpfulOther", "Informative" = "helpfulInformative", "Clear" = "helpfulClear", "Empathetic" = "helpfulEmpathetic", "Good sources" = "helpfulGoodSources", "Unique contex" = "helpfulUniqueContext", "Addresses claim" = "helpfulAddressesClaim", "Important context" = "helpfulImportantContext")|>
    colSums() |>
    tibble::enframe(name = "category", value = "total_count") |>
    ggplot(aes(y =reorder(category, total_count, FUN = sum, decreasing = FALSE), x = total_count)) +
    geom_bar(stat = "identity", fill="darkblue") +
    xlab("Number of Ratings") +
    ylab("") +
    scale_x_continuous(breaks = seq(0, 16000, by = 5000))

```

## Figure 9 Plot

```{r figure-9}
colnames(ratings)

# notHelpfulOpinionSpeculation is not included because no one chooses this option

ratings |>
    select("notHelpfulOther", "notHelpfulIncorrect", "notHelpfulSourcesMissingOrUnreliable", "notHelpfulOpinionSpeculationOrBias", "notHelpfulMissingKeyPoints", "notHelpfulOutdated", "notHelpfulHardToUnderstand", "notHelpfulArgumentativeOrBiased", "notHelpfulOffTopic", "notHelpfulSpamHarassmentOrAbuse", "notHelpfulIrrelevantSources")  |>
     rename_with(~ .x |>
    str_remove("notHelpful") |>
    str_replace_all("([A-Z])", " \\1") |>
    str_to_sentence()
      ) |>
    colSums() |>
    tibble::enframe(name = "category", value = "total_count") |>
    ggplot(aes(y =reorder(category, total_count, FUN = sum, decreasing = FALSE), x = total_count)) +
    geom_bar(stat = "identity", fill="darkred") +
    xlab("Number of Ratings") +
    ylab("") +
    scale_x_continuous(breaks = seq(0, 16000, by = 5000))
```




## Figure 10
```{r figure-10}
source_tweets <- get(load("./data/source_tweets.Rdata"))
head(source_tweets)
colnames(source_tweets)


notes_classification_word_count

filter_source_tweets <- source_tweets |>
  select(noteId, source_account_created_at, source_followers_count, source_friends_count, source_verified)

ratings_filter <- ratings |>
  select(noteId, helpful)

log_reg_df <- inner_join(notes_classification_word_count, filter_source_tweets, by="noteId")
log_reg_df <- inner_join(log_reg_df, ratings_filter, by="noteId")


colnames(log_reg_df)
current_date <- Sys.Date()
current_year <- format(current_date, "%Y")
log_reg_df <- log_reg_df |> 
  mutate(account_age = as.numeric(current_year) - as.numeric(year(log_reg_df$source_account_created_at))) |>
  drop_na()

log_reg_df |>
  str()
#rename to misleading
log_reg_df <- log_reg_df |> rename(misleading = classification, verified = source_verified, followees = source_friends_count)
#made misleading into a binary variable
log_reg_df <- log_reg_df |> mutate(misleading = if_else(misleading == "Misleading", 1, 0, ))
#zstandardize all features
log_reg_df <- log_reg_df |> mutate(across(c(source_followers_count,followees,word_count,account_age), scale))

 

# fitting model
model <- glm(helpful ~ misleading + trustworthySources + word_count + account_age + followees + source_followers_count + verified, data=log_reg_df, family=binomial)
summary(model)
tidy(model)
```







